# Generated by Django 6.0.2 on 2026-02-14 15:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('account_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces')], default='kg', max_length=10)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='CashBankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'Receive'), ('pay', 'Pay')], editable=False, max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.party')),
            ],
        ),
        migrations.CreateModel(
            name='PayMoney',
            fields=[
            ],
            options={
                'verbose_name': 'Pay Money',
                'verbose_name_plural': 'Pay Money',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.cashbanktransaction',),
        ),
        migrations.CreateModel(
            name='ReceiveMoney',
            fields=[
            ],
            options={
                'verbose_name': 'Receive Money',
                'verbose_name_plural': 'Receive Money',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.cashbanktransaction',),
        ),
        migrations.CreateModel(
            name='SalePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase')], editable=False, max_length=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(blank=True, help_text='Required only for cash transactions', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.account')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.inventory')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.party')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.salepurchase',),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.salepurchase',),
        ),
    ]
