# Generated by Django 6.0.2 on 2026-02-14 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='sku',
        ),
        migrations.AddField(
            model_name='party',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Customer: positive means they owe us. Supplier: negative means we owe them.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='credit_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
